// Generated by dart2js, the Dart to JavaScript compiler.
var old$ = $;
$ = Isolate.prototype;

$$ = {};
(function (reflectionData) {
  if (!init.libraries) init.libraries = [];
  var libraries = init.libraries;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var length = reflectionData.length;
  for (var i = 0; i < length; i++) {
    var data = reflectionData[i];
    var name = data[0];
    var descriptor = data[1];
    var classes = [];
    var functions = [];
    for (var property in descriptor) {
      if (!hasOwnProperty.call(descriptor, property)) continue;
      var element = descriptor[property];
      if (typeof element === "function") {
        $[property] = element;
        functions.push(property);
      } else {
        $$[property] = element;
        classes.push(property);
        classes.push(element[""]);
      }
    }
    var uri = ".../library" + i + ".dart";
    libraries.push([name, uri, classes, functions]);
  }
})([
]);
$$ = null;


$ = old$;
